version: '3'
services:
  opensearch-node:
    image: opensearchproject/opensearch:1.0.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  kibana:
    image: opensearchproject/opensearch-dashboards:1.0.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node:9200
    ports:
      - 5601:5601
    depends_on:
      - opensearch-node

volumes:
  opensearch-data1: